const BASIC_SENTENCES = [
    {
        id: "i-drink-water",
        ru: "Я пью воду.",
        answer: ["aš", "geriu", "vandenį"],
        fakeWords: ["tu", "valgau", "duoną", "kavą"],
        fakePools: ["time", "particles", "questions", "pronouns"],
    },
    {
        id: "she-reads-book",
        ru: "Она читает книгу.",
        answer: ["ji", "skaito", "knygą"],
        fakeWords: ["jis", "rašo", "laišką", "namą"],
        fakePools: ["time", "particles", "questions", "pronouns"],
    },
    {
        id: "we-live-in-vilnius",
        ru: "Мы живём в Вильнюсе.",
        answer: ["mes", "gyvename", "vilniuje"],
        fakeWords: ["jūs", "dirbame", "kaune", "rytoj"],
        fakePools: ["time", "particles", "questions", "pronouns"],
    },
    {
        id: "where-is-station",
        ru: "Где находится вокзал?",
        answer: ["kur", "yra", "stotis"],
        fakeWords: ["kas", "namas", "didelė", "eina"],
        fakePools: ["time", "particles", "questions", "pronouns"],
    },
    {
        id: "i-want-coffee",
        ru: "Я хочу кофе.",
        answer: ["aš", "noriu", "kavos"],
        fakeWords: ["tu", "vandens", "turiu", "arbatos"],
        fakePools: ["time", "particles", "questions", "pronouns"],
    },
    {
        id: "children-play-outside",
        ru: "Дети играют на улице.",
        answer: ["vaikai", "žaidžia", "lauke"],
        fakeWords: ["namuose", "miega", "dabar", "šiandien"],
        fakePools: ["time", "particles", "questions", "pronouns"],
    },
    {
        id: "my-friend-speaks-lithuanian",
        ru: "Мой друг говорит по-литовски.",
        answer: ["mano", "draugas", "kalba", "lietuviškai"],
        fakeWords: ["tavo", "rašo", "rusiškai", "mieste"],
        fakePools: ["time", "particles", "questions", "pronouns"],
    },
    {
        id: "tomorrow-we-go-to-school",
        ru: "Завтра мы идём в школу.",
        answer: ["rytoj", "mes", "einame", "į", "mokyklą"],
        fakeWords: ["vakar", "jūs", "iš", "parduotuvę"],
        fakePools: ["time", "particles", "questions", "pronouns"],
    },
    {
        id: "this-soup-is-delicious",
        ru: "Этот суп вкусный.",
        answer: ["ši", "sriuba", "yra", "skani"],
        fakeWords: ["šis", "duona", "buvo", "šaltas"],
        fakePools: ["time", "particles", "questions", "pronouns"],
    },
    {
        id: "i-do-not-understand",
        ru: "Я не понимаю.",
        answer: ["aš", "nesuprantu"],
        fakeWords: ["suprantu", "tu", "kalbu", "gerai"],
        fakePools: ["time", "particles", "questions", "pronouns"],
    },
    {
        id: "they-buy-bread",
        ru: "Они покупают хлеб.",
        answer: ["jie", "perka", "duoną"],
        fakeWords: ["jos", "geria", "pieną", "miestas"],
        fakePools: ["time", "particles", "questions", "pronouns"],
    },
    {
        id: "i-see-house",
        ru: "Я вижу дом.",
        answer: ["aš", "matau", "namą"],
        fakeWords: ["tu", "turiu", "miestą", "knygą"],
        fakePools: ["time", "particles", "questions", "pronouns"],
    },
    {
        id: "you-listen-music",
        ru: "Ты слушаешь музыку.",
        answer: ["tu", "klausai", "muzikos"],
        fakeWords: ["aš", "skaitai", "knygos", "vandens"],
        fakePools: ["time", "particles", "questions", "pronouns"],
    },
    {
        id: "he-works-at-home",
        ru: "Он работает дома.",
        answer: ["jis", "dirba", "namuose"],
        fakeWords: ["ji", "miega", "lauke", "ryte"],
        fakePools: ["time", "particles", "questions", "pronouns"],
    },
    {
        id: "we-eat-breakfast",
        ru: "Мы едим завтрак.",
        answer: ["mes", "valgome", "pusryčius"],
        fakeWords: ["jūs", "geriame", "vakarienę", "kavą"],
        fakePools: ["time", "particles", "questions", "pronouns"],
    },
    {
        id: "they-go-to-park",
        ru: "Они идут в парк.",
        answer: ["jie", "eina", "į", "parką"],
        fakeWords: ["jos", "važiuoja", "iš", "mokyklą"],
        fakePools: ["time", "particles", "questions", "pronouns"],
    },
    {
        id: "i-have-brother",
        ru: "У меня есть брат.",
        answer: ["aš", "turiu", "brolį"],
        fakeWords: ["tu", "noriu", "seserį", "draugą"],
        fakePools: ["time", "particles", "questions", "pronouns"],
    },
    {
        id: "i-like-this-city",
        ru: "Мне нравится этот город.",
        answer: ["man", "patinka", "šis", "miestas"],
        fakeWords: ["tau", "reikia", "ši", "knyga"],
        fakePools: ["time", "particles", "questions", "pronouns"],
    },
    {
        id: "today-is-warm",
        ru: "Сегодня тепло.",
        answer: ["šiandien", "šilta"],
        fakeWords: ["rytoj", "šalta", "namuose", "lyja"],
        fakePools: ["time", "particles", "questions", "pronouns"],
    },
    {
        id: "it-is-raining-now",
        ru: "Сейчас идёт дождь.",
        answer: ["dabar", "lyja"],
        fakeWords: ["vakar", "šviečia", "šalta", "lauke"],
        fakePools: ["time", "particles", "questions", "pronouns"],
    },
    {
        id: "i-learn-lithuanian",
        ru: "Я учу литовский язык.",
        answer: ["aš", "mokausi", "lietuvių", "kalbos"],
        fakeWords: ["tu", "mokau", "anglų", "mieste"],
        fakePools: ["time", "particles", "questions", "pronouns"],
    },
    {
        id: "we-wait-for-bus",
        ru: "Мы ждём автобус.",
        answer: ["mes", "laukiame", "autobuso"],
        fakeWords: ["jūs", "ieškome", "traukinio", "namo"],
        fakePools: ["time", "particles", "questions", "pronouns"],
    },
    {
        id: "i-go-to-work",
        ru: "Я еду на работу.",
        answer: ["aš", "važiuoju", "į", "darbą"],
        fakeWords: ["tu", "einu", "iš", "namus"],
        fakePools: ["time", "particles", "questions", "pronouns"],
    },
    {
        id: "morning-i-drink-tea",
        ru: "Утром я пью чай.",
        answer: ["ryte", "aš", "geriu", "arbatą"],
        fakeWords: ["vakare", "tu", "valgau", "kavą"],
        fakePools: ["time", "particles", "questions", "pronouns"],
    },
    {
        id: "evening-we-watch-movie",
        ru: "Вечером мы смотрим фильм.",
        answer: ["vakare", "mes", "žiūrime", "filmą"],
        fakeWords: ["ryte", "jūs", "skaitome", "laišką"],
        fakePools: ["time", "particles", "questions", "pronouns"],
    },
    {
        id: "dog-sleeps-under-table",
        ru: "Собака спит под столом.",
        answer: ["šuo", "miega", "po", "stalu"],
        fakeWords: ["katė", "sėdi", "ant", "kėdės"],
        fakePools: ["time", "particles", "questions", "pronouns"],
    },
    {
        id: "cat-sits-on-chair",
        ru: "Кошка сидит на стуле.",
        answer: ["katė", "sėdi", "ant", "kėdės"],
        fakeWords: ["šuo", "miega", "po", "stalu"],
        fakePools: ["time", "particles", "questions", "pronouns"],
    },
    {
        id: "my-sister-lives-in-kaunas",
        ru: "Моя сестра живёт в Каунасе.",
        answer: ["mano", "sesuo", "gyvena", "kaune"],
        fakeWords: ["tavo", "brolis", "dirba", "vilniuje"],
        fakePools: ["time", "particles", "questions", "pronouns"],
    },
    {
        id: "i-write-short-letter",
        ru: "Я пишу короткое письмо.",
        answer: ["aš", "rašau", "trumpą", "laišką"],
        fakeWords: ["tu", "skaitau", "ilgą", "knygą"],
        fakePools: ["time", "particles", "questions", "pronouns"],
    },
    {
        id: "you-know-answer",
        ru: "Ты знаешь ответ.",
        answer: ["tu", "žinai", "atsakymą"],
        fakeWords: ["aš", "matai", "klausimą", "miestą"],
        fakePools: ["time", "particles", "questions", "pronouns"],
    },
    {
        id: "we-open-window",
        ru: "Мы открываем окно.",
        answer: ["mes", "atidarome", "langą"],
        fakeWords: ["jūs", "uždarome", "duris", "namą"],
        fakePools: ["time", "particles", "questions", "pronouns"],
    },
    {
        id: "please-close-door",
        ru: "Закройте дверь, пожалуйста.",
        answer: ["prašau", "uždarykite", "duris"],
        fakeWords: ["ačiū", "atidarykite", "langą", "knygą"],
        fakePools: ["time", "particles", "questions", "pronouns"],
    },
    {
        id: "i-need-help",
        ru: "Мне нужна помощь.",
        answer: ["man", "reikia", "pagalbos"],
        fakeWords: ["tau", "patinka", "vandens", "laiko"],
        fakePools: ["time", "particles", "questions", "pronouns"],
    },
    {
        id: "how-much-costs",
        ru: "Сколько это стоит?",
        answer: ["kiek", "tai", "kainuoja"],
        fakeWords: ["kur", "čia", "yra", "dabar"],
        fakePools: ["time", "particles", "questions", "pronouns"],
    },
    {
        id: "i-speak-little-lithuanian",
        ru: "Я немного говорю по-литовски.",
        answer: ["aš", "šiek", "tiek", "kalbu", "lietuviškai"],
        fakeWords: ["tu", "labai", "gerai", "rašau"],
        fakePools: ["time", "particles", "questions", "pronouns"],
    },
    {
        id: "we-often-walk",
        ru: "Мы часто ходим пешком.",
        answer: ["mes", "dažnai", "einame", "pėsčiomis"],
        fakeWords: ["jūs", "retai", "važiuojame", "autobusu"],
        fakePools: ["time", "particles", "questions", "pronouns"],
    },
    {
        id: "shop-has-milk",
        ru: "В магазине есть молоко.",
        answer: ["parduotuvėje", "yra", "pieno"],
        fakeWords: ["namuose", "nėra", "duonos", "vandens"],
        fakePools: ["time", "particles", "questions", "pronouns"],
    },
    {
        id: "this-bread-is-fresh",
        ru: "Этот хлеб свежий.",
        answer: ["ši", "duona", "yra", "šviežia"],
        fakeWords: ["šis", "pienas", "buvo", "šaltas"],
        fakePools: ["time", "particles", "questions", "pronouns"],
    },
    {
        id: "i-do-not-want-to-be-late",
        ru: "Я не хочу опаздывать.",
        answer: ["aš", "nenoriu", "vėluoti"],
        fakeWords: ["tu", "noriu", "laukti", "eiti"],
        fakePools: ["time", "particles", "questions", "pronouns"],
    },
    {
        id: "do-you-have-time",
        ru: "У тебя есть время?",
        answer: ["ar", "tu", "turi", "laiko"],
        fakeWords: ["aš", "kur", "nori", "vandens"],
        fakePools: ["time", "particles", "questions", "pronouns"],
    },
    {
        id: "we-cook-dinner",
        ru: "Мы готовим ужин.",
        answer: ["mes", "gaminame", "vakarienę"],
        fakeWords: ["jūs", "valgome", "pusryčius", "sriubą"],
        fakePools: ["time", "particles", "questions", "pronouns"],
    },
    {
        id: "she-likes-to-read",
        ru: "Она любит читать.",
        answer: ["ji", "mėgsta", "skaityti"],
        fakeWords: ["jis", "nori", "rašyti", "miegoti"],
        fakePools: ["time", "particles", "questions", "pronouns"],
    },
    {
        id: "i-look-for-keys",
        ru: "Я ищу ключи.",
        answer: ["aš", "ieškau", "raktų"],
        fakeWords: ["tu", "laukiu", "durų", "knygų"],
        fakePools: ["time", "particles", "questions", "pronouns"],
    },
    {
        id: "children-go-home",
        ru: "Дети идут домой.",
        answer: ["vaikai", "eina", "namo"],
        fakeWords: ["tėvai", "važiuoja", "lauke", "rytoj"],
        fakePools: ["time", "particles", "questions", "pronouns"],
    },
    {
        id: "we-meet-tomorrow",
        ru: "Мы встретимся завтра.",
        answer: ["mes", "susitiksime", "rytoj"],
        fakeWords: ["jūs", "kalbėsime", "šiandien", "vakar"],
        fakePools: ["time", "particles", "questions", "pronouns"],
    },
    {
        id: "please-repeat",
        ru: "Пожалуйста, повторите ещё раз.",
        answer: ["prašau", "pakartokite", "dar", "kartą"],
        fakeWords: ["ačiū", "pasakykite", "dabar", "namą"],
        fakePools: ["time", "particles", "questions", "pronouns"],
    },
]

const QUESTION_SENTENCES = [
    {
        id: "q-where-do-you-live",
        ru: "Где ты живёшь?",
        answer: ["kur", "tu", "gyveni"],
        fakeWords: ["kada", "aš", "gyvenu", "dirbi"],
        fakePools: ["questions", "pronouns", "places", "time"],
    },
    {
        id: "q-when-do-we-meet",
        ru: "Когда мы встретимся?",
        answer: ["kada", "mes", "susitiksime"],
        fakeWords: ["kur", "jūs", "kalbėsime", "šiandien"],
        fakePools: ["questions", "pronouns", "time", "verbs"],
    },
    {
        id: "q-what-do-you-drink",
        ru: "Что ты пьёшь?",
        answer: ["ką", "tu", "geri"],
        fakeWords: ["ko", "aš", "geriu", "valgai"],
        fakePools: ["questions", "pronouns", "objects", "verbs"],
    },
    {
        id: "q-what-do-you-want",
        ru: "Чего ты хочешь?",
        answer: ["ko", "tu", "nori"],
        fakeWords: ["ką", "aš", "noriu", "turi"],
        fakePools: ["questions", "pronouns", "objects", "verbs"],
    },
    {
        id: "q-do-you-have-time",
        ru: "У тебя есть время?",
        answer: ["ar", "tu", "turi", "laiko"],
        fakeWords: ["kur", "aš", "nori", "vandens"],
        fakePools: ["questions", "pronouns", "time", "objects"],
    },
    {
        id: "q-why-is-he-late",
        ru: "Почему он опаздывает?",
        answer: ["kodėl", "jis", "vėluoja"],
        fakeWords: ["kada", "ji", "eina", "anksti"],
        fakePools: ["questions", "pronouns", "time", "verbs"],
    },
    {
        id: "q-how-do-you-feel",
        ru: "Как ты себя чувствуешь?",
        answer: ["kaip", "tu", "jautiesi"],
        fakeWords: ["kur", "aš", "jaučiuosi", "gyveni"],
        fakePools: ["questions", "pronouns", "time", "verbs"],
    },
    {
        id: "q-how-much-ticket-costs",
        ru: "Сколько стоит билет?",
        answer: ["kiek", "kainuoja", "bilietas"],
        fakeWords: ["kur", "yra", "pinigai", "dabar"],
        fakePools: ["questions", "particles", "objects", "time"],
    },
    {
        id: "q-where-is-station",
        ru: "Где находится вокзал?",
        answer: ["kur", "yra", "stotis"],
        fakeWords: ["kas", "čia", "namas", "eina"],
        fakePools: ["questions", "places", "particles", "verbs"],
    },
    {
        id: "q-who-reads-book",
        ru: "Кто читает книгу?",
        answer: ["kas", "skaito", "knygą"],
        fakeWords: ["ką", "rašo", "laišką", "ji"],
        fakePools: ["questions", "pronouns", "objects", "verbs"],
    },
    {
        id: "q-who-needs-help",
        ru: "Кому нужна помощь?",
        answer: ["kam", "reikia", "pagalbos"],
        fakeWords: ["kas", "patinka", "vandens", "tau"],
        fakePools: ["questions", "pronouns", "objects", "verbs"],
    },
    {
        id: "q-with-whom-you-speak",
        ru: "С кем ты говоришь?",
        answer: ["su", "kuo", "tu", "kalbi"],
        fakeWords: ["be", "ko", "aš", "rašai"],
        fakePools: ["questions", "particles", "pronouns", "verbs"],
    },
    {
        id: "q-which-city-we-go-to",
        ru: "В какой город мы едем?",
        answer: ["į", "kurį", "miestą", "mes", "važiuojame"],
        fakeWords: ["iš", "kuri", "mieste", "jūs", "einame"],
        fakePools: ["questions", "particles", "pronouns", "places"],
    },
    {
        id: "q-which-book-is-yours",
        ru: "Какая книга твоя?",
        answer: ["kuri", "knyga", "yra", "tavo"],
        fakeWords: ["kuris", "namas", "mano", "čia"],
        fakePools: ["questions", "pronouns", "objects", "particles"],
    },
    {
        id: "q-is-it-raining-today",
        ru: "Сегодня идёт дождь?",
        answer: ["ar", "šiandien", "lyja"],
        fakeWords: ["kur", "rytoj", "šviečia", "dabar"],
        fakePools: ["questions", "time", "particles", "places"],
    },
    {
        id: "q-where-is-my-phone",
        ru: "Где мой телефон?",
        answer: ["kur", "mano", "telefonas"],
        fakeWords: ["kada", "tavo", "raktai", "čia"],
        fakePools: ["questions", "pronouns", "places", "particles"],
    },
    {
        id: "q-when-lesson-starts",
        ru: "Когда начинается урок?",
        answer: ["kada", "prasideda", "pamoka"],
        fakeWords: ["kur", "baigiasi", "darbas", "vėlai"],
        fakePools: ["questions", "time", "verbs", "places"],
    },
    {
        id: "q-how-to-go-to-center",
        ru: "Как пройти до центра?",
        answer: ["kaip", "nueiti", "iki", "centro"],
        fakeWords: ["kur", "važiuoti", "į", "namų"],
        fakePools: ["questions", "particles", "places", "verbs"],
    },
    {
        id: "q-can-you-repeat",
        ru: "Можешь повторить?",
        answer: ["ar", "gali", "pakartoti"],
        fakeWords: ["ką", "nori", "pasakyti", "dabar"],
        fakePools: ["questions", "time", "verbs", "pronouns"],
    },
    {
        id: "q-what-do-you-eat-for-breakfast",
        ru: "Что ты ешь на завтрак?",
        answer: ["ką", "valgai", "pusryčiams"],
        fakeWords: ["ko", "geri", "vakarienei", "duoną"],
        fakePools: ["questions", "objects", "time", "verbs"],
    },
    {
        id: "q-what-day-is-today",
        ru: "Какой сегодня день?",
        answer: ["kokia", "šiandien", "diena"],
        fakeWords: ["koks", "rytoj", "laikas", "vakar"],
        fakePools: ["questions", "time", "objects", "particles"],
    },
    {
        id: "q-where-are-you-going",
        ru: "Куда ты идёшь?",
        answer: ["kur", "tu", "eini"],
        fakeWords: ["kada", "aš", "einu", "važiuoji"],
        fakePools: ["questions", "pronouns", "places", "verbs"],
    },
    {
        id: "q-what-are-you-looking-for",
        ru: "Что ты ищешь?",
        answer: ["ko", "tu", "ieškai"],
        fakeWords: ["ką", "aš", "ieškau", "lauki"],
        fakePools: ["questions", "pronouns", "objects", "verbs"],
    },
    {
        id: "q-is-store-open",
        ru: "Магазин открыт?",
        answer: ["ar", "parduotuvė", "atidaryta"],
        fakeWords: ["kur", "mokykla", "uždaryta", "dabar"],
        fakePools: ["questions", "places", "time", "particles"],
    },
    {
        id: "q-why-do-you-learn-lithuanian",
        ru: "Почему ты учишь литовский?",
        answer: ["kodėl", "tu", "mokaisi", "lietuvių"],
        fakeWords: ["kaip", "aš", "mokau", "anglų"],
        fakePools: ["questions", "pronouns", "objects", "verbs"],
    },
    {
        id: "q-where-can-i-buy-water",
        ru: "Где я могу купить воду?",
        answer: ["kur", "aš", "galiu", "nusipirkti", "vandens"],
        fakeWords: ["kada", "tu", "gali", "parduoti", "duonos"],
        fakePools: ["questions", "pronouns", "objects", "places"],
    },
    {
        id: "q-what-is-your-name",
        ru: "Как тебя зовут?",
        answer: ["koks", "tavo", "vardas"],
        fakeWords: ["kokia", "mano", "miestas", "čia"],
        fakePools: ["questions", "pronouns", "particles", "objects"],
    },
    {
        id: "q-where-is-bus-stop",
        ru: "Где остановка автобуса?",
        answer: ["kur", "yra", "autobusų", "stotelė"],
        fakeWords: ["kada", "čia", "traukinio", "stotis"],
        fakePools: ["questions", "places", "particles", "objects"],
    },
    {
        id: "q-does-she-speak-russian",
        ru: "Она говорит по-русски?",
        answer: ["ar", "ji", "kalba", "rusiškai"],
        fakeWords: ["kur", "jis", "rašo", "lietuviškai"],
        fakePools: ["questions", "pronouns", "verbs", "objects"],
    },
    {
        id: "q-what-time-is-it",
        ru: "Который час?",
        answer: ["kiek", "dabar", "valandų"],
        fakeWords: ["kur", "rytoj", "minučių", "laiko"],
        fakePools: ["questions", "time", "objects", "particles"],
    },
]

const PAST_FUTURE_SENTENCES = [
    {
        id: "pf-yesterday-i-drank-coffee",
        ru: "Вчера я пил кофе.",
        answer: ["vakar", "aš", "gėriau", "kavą"],
        fakeWords: ["rytoj", "tu", "geriu", "arbatą"],
        fakePools: ["time", "pronouns", "objects", "verbs"],
    },
    {
        id: "pf-tomorrow-i-will-drink-tea",
        ru: "Завтра я буду пить чай.",
        answer: ["rytoj", "aš", "gersiu", "arbatą"],
        fakeWords: ["vakar", "tu", "gėriau", "kavą"],
        fakePools: ["time", "pronouns", "objects", "verbs"],
    },
    {
        id: "pf-yesterday-we-went-store",
        ru: "Вчера мы ходили в магазин.",
        answer: ["vakar", "mes", "ėjome", "į", "parduotuvę"],
        fakeWords: ["rytoj", "jūs", "einame", "iš", "mokyklą"],
        fakePools: ["time", "pronouns", "places", "particles"],
    },
    {
        id: "pf-tomorrow-we-will-go-park",
        ru: "Завтра мы пойдём в парк.",
        answer: ["rytoj", "mes", "eisime", "į", "parką"],
        fakeWords: ["vakar", "jūs", "ėjome", "iš", "parduotuvę"],
        fakePools: ["time", "pronouns", "places", "particles"],
    },
    {
        id: "pf-she-read-book",
        ru: "Она прочитала книгу.",
        answer: ["ji", "skaitė", "knygą"],
        fakeWords: ["jis", "skaitys", "laišką", "skaito"],
        fakePools: ["pronouns", "objects", "verbs", "time"],
    },
    {
        id: "pf-she-will-read-book",
        ru: "Она прочитает книгу.",
        answer: ["ji", "skaitys", "knygą"],
        fakeWords: ["jis", "skaitė", "laišką", "skaito"],
        fakePools: ["pronouns", "objects", "verbs", "time"],
    },
    {
        id: "pf-he-wrote-letter",
        ru: "Он написал письмо.",
        answer: ["jis", "rašė", "laišką"],
        fakeWords: ["ji", "rašys", "knygą", "rašo"],
        fakePools: ["pronouns", "objects", "verbs", "time"],
    },
    {
        id: "pf-he-will-write-letter",
        ru: "Он напишет письмо.",
        answer: ["jis", "rašys", "laišką"],
        fakeWords: ["ji", "rašė", "knygą", "rašo"],
        fakePools: ["pronouns", "objects", "verbs", "time"],
    },
    {
        id: "pf-they-bought-bread",
        ru: "Они купили хлеб.",
        answer: ["jie", "pirko", "duoną"],
        fakeWords: ["jos", "pirks", "pieną", "perka"],
        fakePools: ["pronouns", "objects", "verbs", "time"],
    },
    {
        id: "pf-they-will-buy-bread",
        ru: "Они купят хлеб.",
        answer: ["jie", "pirks", "duoną"],
        fakeWords: ["jos", "pirko", "pieną", "perka"],
        fakePools: ["pronouns", "objects", "verbs", "time"],
    },
    {
        id: "pf-i-lived-vilnius",
        ru: "Я жил в Вильнюсе.",
        answer: ["aš", "gyvenau", "vilniuje"],
        fakeWords: ["tu", "gyvensiu", "kaune", "gyvenu"],
        fakePools: ["pronouns", "places", "time", "verbs"],
    },
    {
        id: "pf-i-will-live-kaunas",
        ru: "Я буду жить в Каунасе.",
        answer: ["aš", "gyvensiu", "kaune"],
        fakeWords: ["tu", "gyvenau", "vilniuje", "gyvenu"],
        fakePools: ["pronouns", "places", "time", "verbs"],
    },
    {
        id: "pf-we-cooked-dinner",
        ru: "Мы готовили ужин.",
        answer: ["mes", "gaminome", "vakarienę"],
        fakeWords: ["jūs", "gaminsime", "pusryčius", "gaminame"],
        fakePools: ["pronouns", "objects", "time", "verbs"],
    },
    {
        id: "pf-we-will-cook-dinner",
        ru: "Мы приготовим ужин.",
        answer: ["mes", "gaminsime", "vakarienę"],
        fakeWords: ["jūs", "gaminome", "pusryčius", "gaminame"],
        fakePools: ["pronouns", "objects", "time", "verbs"],
    },
    {
        id: "pf-i-learned-lithuanian",
        ru: "Я учил литовский.",
        answer: ["aš", "mokiausi", "lietuvių"],
        fakeWords: ["tu", "mokysiuosi", "anglų", "mokausi"],
        fakePools: ["pronouns", "objects", "time", "verbs"],
    },
    {
        id: "pf-i-will-learn-lithuanian",
        ru: "Я буду учить литовский.",
        answer: ["aš", "mokysiuosi", "lietuvių"],
        fakeWords: ["tu", "mokiausi", "anglų", "mokausi"],
        fakePools: ["pronouns", "objects", "time", "verbs"],
    },
    {
        id: "pf-we-met-yesterday",
        ru: "Мы встретились вчера.",
        answer: ["mes", "susitikome", "vakar"],
        fakeWords: ["jūs", "susitiksime", "rytoj", "susitinkame"],
        fakePools: ["pronouns", "time", "verbs", "places"],
    },
    {
        id: "pf-we-will-meet-tomorrow",
        ru: "Мы встретимся завтра.",
        answer: ["mes", "susitiksime", "rytoj"],
        fakeWords: ["jūs", "susitikome", "vakar", "susitinkame"],
        fakePools: ["pronouns", "time", "verbs", "places"],
    },
    {
        id: "pf-they-waited-bus",
        ru: "Они ждали автобус.",
        answer: ["jie", "laukė", "autobuso"],
        fakeWords: ["jos", "lauks", "traukinio", "laukia"],
        fakePools: ["pronouns", "objects", "time", "verbs"],
    },
    {
        id: "pf-they-will-wait-bus",
        ru: "Они будут ждать автобус.",
        answer: ["jie", "lauks", "autobuso"],
        fakeWords: ["jos", "laukė", "traukinio", "laukia"],
        fakePools: ["pronouns", "objects", "time", "verbs"],
    },
    {
        id: "pf-i-looked-for-keys",
        ru: "Я искал ключи.",
        answer: ["aš", "ieškojau", "raktų"],
        fakeWords: ["tu", "ieškosiu", "durų", "ieškau"],
        fakePools: ["pronouns", "objects", "time", "verbs"],
    },
    {
        id: "pf-i-will-look-for-keys",
        ru: "Я буду искать ключи.",
        answer: ["aš", "ieškosiu", "raktų"],
        fakeWords: ["tu", "ieškojau", "durų", "ieškau"],
        fakePools: ["pronouns", "objects", "time", "verbs"],
    },
    {
        id: "pf-yesterday-it-rained",
        ru: "Вчера шёл дождь.",
        answer: ["vakar", "lijo"],
        fakeWords: ["rytoj", "lis", "lyja", "šalta"],
        fakePools: ["time", "places", "particles", "verbs"],
    },
    {
        id: "pf-tomorrow-it-will-rain",
        ru: "Завтра будет дождь.",
        answer: ["rytoj", "lis"],
        fakeWords: ["vakar", "lijo", "lyja", "šilta"],
        fakePools: ["time", "places", "particles", "verbs"],
    },
    {
        id: "pf-last-week-i-worked-home",
        ru: "На прошлой неделе я работал дома.",
        answer: ["praėjusią", "savaitę", "aš", "dirbau", "namuose"],
        fakeWords: ["kitą", "savaitę", "tu", "dirbsiu", "lauke"],
        fakePools: ["time", "pronouns", "places", "verbs"],
    },
    {
        id: "pf-next-week-i-will-work-home",
        ru: "На следующей неделе я буду работать дома.",
        answer: ["kitą", "savaitę", "aš", "dirbsiu", "namuose"],
        fakeWords: ["praėjusią", "savaitę", "tu", "dirbau", "lauke"],
        fakePools: ["time", "pronouns", "places", "verbs"],
    },
    {
        id: "pf-morning-i-opened-window",
        ru: "Утром я открыл окно.",
        answer: ["ryte", "aš", "atidariau", "langą"],
        fakeWords: ["vakare", "tu", "atidarysiu", "duris"],
        fakePools: ["time", "pronouns", "objects", "verbs"],
    },
    {
        id: "pf-evening-i-will-close-door",
        ru: "Вечером я закрою дверь.",
        answer: ["vakare", "aš", "uždarysiu", "duris"],
        fakeWords: ["ryte", "tu", "uždariau", "langą"],
        fakePools: ["time", "pronouns", "objects", "verbs"],
    },
    {
        id: "pf-yesterday-she-called-me",
        ru: "Вчера она мне звонила.",
        answer: ["vakar", "ji", "man", "skambino"],
        fakeWords: ["rytoj", "jis", "tau", "skambins"],
        fakePools: ["time", "pronouns", "verbs", "particles"],
    },
    {
        id: "pf-tomorrow-she-will-call-me",
        ru: "Завтра она мне позвонит.",
        answer: ["rytoj", "ji", "man", "skambins"],
        fakeWords: ["vakar", "jis", "tau", "skambino"],
        fakePools: ["time", "pronouns", "verbs", "particles"],
    },
    {
        id: "pf-yesterday-children-played-outside",
        ru: "Вчера дети играли на улице.",
        answer: ["vakar", "vaikai", "žaidė", "lauke"],
        fakeWords: ["rytoj", "tėvai", "žais", "namuose"],
        fakePools: ["time", "places", "verbs", "pronouns"],
    },
    {
        id: "pf-tomorrow-children-will-play-outside",
        ru: "Завтра дети будут играть на улице.",
        answer: ["rytoj", "vaikai", "žais", "lauke"],
        fakeWords: ["vakar", "tėvai", "žaidė", "namuose"],
        fakePools: ["time", "places", "verbs", "pronouns"],
    },
]

export const SENTENCE_PACKS = [
    {
        id: "basic",
        title: "Начальный пак",
        description: "Базовые бытовые предложения и частые конструкции.",
        sentences: BASIC_SENTENCES,
    },
    {
        id: "questions",
        title: "Вопросы",
        description: "Бытовые вопросы: где, когда, сколько, почему, что и как.",
        sentences: QUESTION_SENTENCES,
    },
    {
        id: "past-future",
        title: "Прошлое и будущее",
        description: "Пары бытовых фраз в прошедшем и будущем времени.",
        sentences: PAST_FUTURE_SENTENCES,
    },
]

export const DEFAULT_SENTENCE_PACK_IDS = ["basic"]

export const SENTENCE_BANK = SENTENCE_PACKS.flatMap((pack) => pack.sentences)

export function sentencePackById(id) {
    return SENTENCE_PACKS.find((pack) => pack.id === id) || null
}

export function sentencePackIds() {
    return SENTENCE_PACKS.map((pack) => pack.id)
}

export function sentencesForPackIds(ids) {
    if (!Array.isArray(ids) || !ids.length) return []
    const selected = new Set(ids)
    return SENTENCE_PACKS.filter((pack) => selected.has(pack.id)).flatMap((pack) => pack.sentences)
}

export function sentenceToRoundWord(sentence) {
    return {
        id: `sentence-${sentence.id}`,
        type: "sentence",
        lemma: sentence.answer.join(" "),
        forms: {},
        translations: [sentence.ru],
    }
}

export function sentenceExpectedText(sentence) {
    return Array.isArray(sentence?.answer) ? sentence.answer.join(" ") : ""
}
